var searchData=
[
  ['saiex_0',['SAIEx',['../group___s_a_i_ex.html',1,'']]],
  ['sau_20functions_1',['SAU Functions',['../group___c_m_s_i_s___core___s_a_u_functions.html',1,'']]],
  ['scopedlock_20functions_2',['ScopedLock functions',['../group__platform___scoped_lock.html',1,'']]],
  ['serial_20protocol_3',['Serial Protocol',['../group___s_p_i___l_l___e_c___p_r_o_t_o_c_o_l.html',1,'']]],
  ['shift_20second_4',['SHIFT SECOND',['../group___r_t_c___l_l___e_c___s_h_i_f_t___s_e_c_o_n_d.html',1,'']]],
  ['sine_5',['Sine',['../group__sin.html',1,'']]],
  ['sine_20cosine_20_20_20_3cbr_3e_6',['Sine Cosine   &lt;br&gt;',['../group___sin_cos.html',1,'']]],
  ['singletonptr_20class_7',['SingletonPtr class',['../group__platform___singleton_ptr.html',1,'']]],
  ['slave_20mode_8',['Slave Mode',['../group___t_i_m___l_l___e_c___s_l_a_v_e_m_o_d_e.html',1,'']]],
  ['slave_20select_20pin_20management_9',['Slave Select Pin Management',['../group___s_p_i___l_l___e_f___n_s_s___management.html',1,'']]],
  ['slave_20select_20pin_20mode_10',['Slave Select Pin Mode',['../group___s_p_i___l_l___e_c___n_s_s___m_o_d_e.html',1,'']]],
  ['sleep_20manager_20api_11',['Sleep manager API',['../group__hal__sleep__manager.html',1,'']]],
  ['sleep_20manager_20api_20tests_12',['Sleep manager API tests',['../group__hal__sleep__manager__tests.html',1,'']]],
  ['smartcard_13',['SMARTCARD',['../group___s_m_a_r_t_c_a_r_d.html',1,'']]],
  ['smartcard_20clock_20phase_14',['SMARTCARD Clock Phase',['../group___s_m_a_r_t_c_a_r_d___clock___phase.html',1,'']]],
  ['smartcard_20clock_20polarity_15',['SMARTCARD Clock Polarity',['../group___s_m_a_r_t_c_a_r_d___clock___polarity.html',1,'']]],
  ['smartcard_20dma_20requests_16',['SMARTCARD DMA requests',['../group___s_m_a_r_t_c_a_r_d___d_m_a___requests.html',1,'']]],
  ['smartcard_20error_20code_17',['SMARTCARD Error Code',['../group___s_m_a_r_t_c_a_r_d___error___code.html',1,'']]],
  ['smartcard_20exported_20constants_18',['SMARTCARD Exported constants',['../group___s_m_a_r_t_c_a_r_d___exported___constants.html',1,'']]],
  ['smartcard_20exported_20macros_19',['SMARTCARD Exported Macros',['../group___s_m_a_r_t_c_a_r_d___exported___macros.html',1,'']]],
  ['smartcard_20exported_20types_20',['SMARTCARD Exported Types',['../group___s_m_a_r_t_c_a_r_d___exported___types.html',1,'']]],
  ['smartcard_20flags_21',['SMARTCARD Flags',['../group___smart_card___flags.html',1,'']]],
  ['smartcard_20interrupts_20definition_22',['SMARTCARD Interrupts Definition',['../group___smart_card___interrupt__definition.html',1,'']]],
  ['smartcard_20last_20bit_23',['SMARTCARD Last Bit',['../group___s_m_a_r_t_c_a_r_d___last___bit.html',1,'']]],
  ['smartcard_20mode_24',['SMARTCARD Mode',['../group___s_m_a_r_t_c_a_r_d___mode.html',1,'']]],
  ['smartcard_20nack_20state_25',['SMARTCARD NACK State',['../group___s_m_a_r_t_c_a_r_d___n_a_c_k___state.html',1,'']]],
  ['smartcard_20number_20of_20stop_20bits_26',['SMARTCARD Number of Stop Bits',['../group___s_m_a_r_t_c_a_r_d___stop___bits.html',1,'']]],
  ['smartcard_20parity_27',['SMARTCARD Parity',['../group___s_m_a_r_t_c_a_r_d___parity.html',1,'']]],
  ['smartcard_20prescaler_28',['SMARTCARD Prescaler',['../group___s_m_a_r_t_c_a_r_d___prescaler.html',1,'']]],
  ['smartcard_20private_20constants_29',['SMARTCARD Private Constants',['../group___s_m_a_r_t_c_a_r_d___private___constants.html',1,'']]],
  ['smartcard_20private_20functions_30',['SMARTCARD Private Functions',['../group___s_m_a_r_t_c_a_r_d___private___functions.html',1,'']]],
  ['smartcard_20private_20macros_31',['SMARTCARD Private Macros',['../group___s_m_a_r_t_c_a_r_d___private___macros.html',1,'']]],
  ['smartcard_20word_20length_32',['SMARTCARD Word Length',['../group___s_m_a_r_t_c_a_r_d___word___length.html',1,'']]],
  ['smartcard_5fexported_5ffunctions_33',['SMARTCARD_Exported_Functions',['../group___s_m_a_r_t_c_a_r_d___exported___functions.html',1,'']]],
  ['smartcard_5fexported_5ffunctions_5fgroup1_34',['SMARTCARD_Exported_Functions_Group1',['../group___s_m_a_r_t_c_a_r_d___exported___functions___group1.html',1,'']]],
  ['smartcard_5fexported_5ffunctions_5fgroup2_35',['SMARTCARD_Exported_Functions_Group2',['../group___s_m_a_r_t_c_a_r_d___exported___functions___group2.html',1,'']]],
  ['smartcard_5fexported_5ffunctions_5fgroup3_36',['SMARTCARD_Exported_Functions_Group3',['../group___s_m_a_r_t_c_a_r_d___exported___functions___group3.html',1,'']]],
  ['software_5finterrupt_5fmanagement_37',['Software_Interrupt_Management',['../group___e_x_t_i___l_l___e_f___software___interrupt___management.html',1,'']]],
  ['span_20class_38',['Span class',['../group__platform___span.html',1,'']]],
  ['spi_39',['SPI',['../group___s_p_i.html',1,'(Global Namespace)'],['../group___s_p_i___l_l.html',1,'(Global Namespace)']]],
  ['spi_20baudrate_20prescaler_40',['SPI BaudRate Prescaler',['../group___s_p_i___baud_rate___prescaler.html',1,'']]],
  ['spi_20clock_20phase_41',['SPI Clock Phase',['../group___s_p_i___clock___phase.html',1,'']]],
  ['spi_20clock_20polarity_42',['SPI Clock Polarity',['../group___s_p_i___clock___polarity.html',1,'']]],
  ['spi_20crc_20calculation_43',['SPI CRC Calculation',['../group___s_p_i___c_r_c___calculation.html',1,'']]],
  ['spi_20data_20size_44',['SPI Data Size',['../group___s_p_i___data___size.html',1,'']]],
  ['spi_20direction_20mode_45',['SPI Direction Mode',['../group___s_p_i___direction.html',1,'']]],
  ['spi_20error_20code_46',['SPI Error Code',['../group___s_p_i___error___code.html',1,'']]],
  ['spi_20exported_20constants_47',['SPI Exported Constants',['../group___s_p_i___exported___constants.html',1,'(Global Namespace)'],['../group___s_p_i___l_l___exported___constants.html',1,'(Global Namespace)']]],
  ['spi_20exported_20functions_48',['SPI Exported Functions',['../group___s_p_i___l_l___exported___functions.html',1,'']]],
  ['spi_20exported_20macros_49',['SPI Exported Macros',['../group___s_p_i___exported___macros.html',1,'(Global Namespace)'],['../group___s_p_i___l_l___exported___macros.html',1,'(Global Namespace)']]],
  ['spi_20exported_20types_50',['SPI Exported Types',['../group___s_p_i___exported___types.html',1,'']]],
  ['spi_20flags_20definition_51',['SPI Flags Definition',['../group___s_p_i___flags__definition.html',1,'']]],
  ['spi_20interrupt_20definition_52',['SPI Interrupt Definition',['../group___s_p_i___interrupt__definition.html',1,'']]],
  ['spi_20mode_53',['SPI Mode',['../group___s_p_i___mode.html',1,'']]],
  ['spi_20msb_20lsb_20transmission_54',['SPI MSB LSB Transmission',['../group___s_p_i___m_s_b___l_s_b__transmission.html',1,'']]],
  ['spi_20private_20functions_55',['SPI Private Functions',['../group___s_p_i___private___functions.html',1,'']]],
  ['spi_20private_20macros_56',['SPI Private Macros',['../group___s_p_i___private___macros.html',1,'']]],
  ['spi_20slave_20select_20management_57',['SPI Slave Select Management',['../group___s_p_i___slave___select__management.html',1,'']]],
  ['spi_20ti_20mode_58',['SPI TI Mode',['../group___s_p_i___t_i__mode.html',1,'']]],
  ['spi_5fexported_5ffunctions_59',['SPI_Exported_Functions',['../group___s_p_i___exported___functions.html',1,'']]],
  ['spi_5fexported_5ffunctions_5fgroup1_60',['SPI_Exported_Functions_Group1',['../group___s_p_i___exported___functions___group1.html',1,'']]],
  ['spi_5fexported_5ffunctions_5fgroup2_61',['SPI_Exported_Functions_Group2',['../group___s_p_i___exported___functions___group2.html',1,'']]],
  ['spi_5fexported_5ffunctions_5fgroup3_62',['SPI_Exported_Functions_Group3',['../group___s_p_i___exported___functions___group3.html',1,'']]],
  ['square_20root_63',['Square Root',['../group___s_q_r_t.html',1,'']]],
  ['standard_20deviation_20_20_20_20_3cbr_3e_64',['Standard deviation    &lt;br&gt;',['../group___s_t_d.html',1,'']]],
  ['statistics_20functions_65',['Statistics Functions',['../group__group_stats.html',1,'']]],
  ['stats_20functions_66',['stats functions',['../group__platform__stats.html',1,'']]],
  ['status_20and_20control_20registers_67',['Status and Control Registers',['../group___c_m_s_i_s___c_o_r_e.html',1,'']]],
  ['stm32f401xe_68',['Stm32f401xe',['../group__stm32f401xe.html',1,'']]],
  ['stm32f4xx_69',['Stm32f4xx',['../group__stm32f4xx.html',1,'']]],
  ['stm32f4xx_5fhal_5fdriver_70',['STM32F4xx_HAL_Driver',['../group___s_t_m32_f4xx___h_a_l___driver.html',1,'']]],
  ['stm32f4xx_5fll_5fdriver_71',['STM32F4xx_LL_Driver',['../group___s_t_m32_f4xx___l_l___driver.html',1,'']]],
  ['stm32f4xx_5fsystem_72',['Stm32f4xx_system',['../group__stm32f4xx__system.html',1,'']]],
  ['stm32f4xx_5fsystem_5fexported_5fconstants_73',['STM32F4xx_System_Exported_Constants',['../group___s_t_m32_f4xx___system___exported___constants.html',1,'']]],
  ['stm32f4xx_5fsystem_5fexported_5ffunctions_74',['STM32F4xx_System_Exported_Functions',['../group___s_t_m32_f4xx___system___exported___functions.html',1,'']]],
  ['stm32f4xx_5fsystem_5fexported_5fmacros_75',['STM32F4xx_System_Exported_Macros',['../group___s_t_m32_f4xx___system___exported___macros.html',1,'']]],
  ['stm32f4xx_5fsystem_5fexported_5ftypes_76',['STM32F4xx_System_Exported_types',['../group___s_t_m32_f4xx___system___exported__types.html',1,'']]],
  ['stm32f4xx_5fsystem_5fincludes_77',['STM32F4xx_System_Includes',['../group___s_t_m32_f4xx___system___includes.html',1,'']]],
  ['stop_20bits_78',['Stop Bits',['../group___u_s_a_r_t___l_l___e_c___s_t_o_p_b_i_t_s.html',1,'']]],
  ['stream_79',['STREAM',['../group___d_m_a___l_l___e_c___s_t_r_e_a_m.html',1,'']]],
  ['stream_20class_80',['Stream class',['../group__platform___stream.html',1,'']]],
  ['support_20functions_81',['Support Functions',['../group__group_support.html',1,'']]],
  ['syscfg_82',['SYSCFG',['../group___s_y_s_t_e_m___l_l___e_f___s_y_s_c_f_g.html',1,'']]],
  ['syscfg_20exti_20line_83',['SYSCFG EXTI LINE',['../group___s_y_s_t_e_m___l_l___e_c___e_x_t_i___l_i_n_e.html',1,'']]],
  ['syscfg_20exti_20port_84',['SYSCFG EXTI PORT',['../group___s_y_s_t_e_m___l_l___e_c___e_x_t_i___p_o_r_t.html',1,'']]],
  ['syscfg_20i2c_20fastmodeplus_85',['SYSCFG I2C FASTMODEPLUS',['../group___s_y_s_t_e_m___l_l___e_c___i2_c___f_a_s_t_m_o_d_e_p_l_u_s.html',1,'']]],
  ['syscfg_20remap_86',['SYSCFG REMAP',['../group___s_y_s_t_e_m___l_l___e_c___r_e_m_a_p.html',1,'']]],
  ['syscfg_20timer_20break_87',['SYSCFG TIMER BREAK',['../group___s_y_s_t_e_m___l_l___e_c___t_i_m_b_r_e_a_k.html',1,'']]],
  ['system_88',['System',['../group___r_c_c___l_l___e_f___system.html',1,'']]],
  ['system_89',['SYSTEM',['../group___s_y_s_t_e_m___l_l.html',1,'(Global Namespace)'],['../group___u_t_i_l_s___e_f___s_y_s_t_e_m.html',1,'(Global Namespace)']]],
  ['system_20clock_20source_90',['System Clock Source',['../group___r_c_c___system___clock___source.html',1,'']]],
  ['system_20clock_20source_20status_91',['System Clock Source Status',['../group___r_c_c___system___clock___source___status.html',1,'']]],
  ['system_20clock_20switch_92',['System clock switch',['../group___r_c_c___l_l___e_c___s_y_s___c_l_k_s_o_u_r_c_e.html',1,'']]],
  ['system_20clock_20switch_20status_93',['System clock switch status',['../group___r_c_c___l_l___e_c___s_y_s___c_l_k_s_o_u_r_c_e___s_t_a_t_u_s.html',1,'']]],
  ['system_20clock_20type_94',['System Clock Type',['../group___r_c_c___system___clock___type.html',1,'']]],
  ['system_20control_20block_20_28scb_29_95',['System Control Block (SCB)',['../group___c_m_s_i_s___s_c_b.html',1,'']]],
  ['system_20controls_20not_20in_20scb_20_28scnscb_29_96',['System Controls not in SCB (SCnSCB)',['../group___c_m_s_i_s___s_cn_s_c_b.html',1,'']]],
  ['system_20exported_20constants_97',['SYSTEM Exported Constants',['../group___s_y_s_t_e_m___l_l___exported___constants.html',1,'']]],
  ['system_20exported_20functions_98',['SYSTEM Exported Functions',['../group___s_y_s_t_e_m___l_l___exported___functions.html',1,'']]],
  ['system_20private_20constants_99',['SYSTEM Private Constants',['../group___s_y_s_t_e_m___l_l___private___constants.html',1,'']]],
  ['system_20tick_20timer_20_28systick_29_100',['System Tick Timer (SysTick)',['../group___c_m_s_i_s___sys_tick.html',1,'']]],
  ['systick_101',['SYSTICK',['../group___c_o_r_t_e_x___l_l___e_f___s_y_s_t_i_c_k.html',1,'']]],
  ['systick_20clock_20source_102',['SYSTICK Clock Source',['../group___c_o_r_t_e_x___l_l___e_c___c_l_k_s_o_u_r_c_e___h_c_l_k.html',1,'']]],
  ['systick_20functions_103',['SysTick Functions',['../group___c_m_s_i_s___core___sys_tick_functions.html',1,'']]]
];
