var searchData=
[
  ['cache_20functions_0',['Cache Functions',['../group___c_m_s_i_s___core___cache_functions.html',1,'']]],
  ['calculate_20frequencies_1',['Calculate frequencies',['../group___r_c_c___l_l___e_m___c_a_l_c___f_r_e_q.html',1,'']]],
  ['calibration_2',['Calibration',['../group___r_t_c___l_l___e_f___calibration.html',1,'']]],
  ['calibration_20output_3',['Calibration output',['../group___r_t_c___l_l___e_c___c_a_l_i_b___o_u_t_p_u_t.html',1,'']]],
  ['calibration_20period_4',['Calibration period',['../group___r_t_c___l_l___e_c___c_a_l_i_b___p_e_r_i_o_d.html',1,'']]],
  ['calibration_20pulse_20insertion_5',['Calibration pulse insertion',['../group___r_t_c___l_l___e_c___c_a_l_i_b___i_n_s_e_r_t_p_u_l_s_e.html',1,'']]],
  ['callback_20class_6',['Callback class',['../group__platform___callback.html',1,'']]],
  ['callchain_20class_7',['CallChain class',['../group__platform___call_chain.html',1,'']]],
  ['capture_20compare_20_20update_20source_8',['Capture Compare  Update Source',['../group___t_i_m___l_l___e_c___c_c_u_p_d_a_t_e_s_o_u_r_c_e.html',1,'']]],
  ['capture_20compare_20configuration_9',['Capture Compare configuration',['../group___t_i_m___l_l___e_f___capture___compare.html',1,'']]],
  ['capture_20compare_20dma_20request_10',['Capture Compare DMA Request',['../group___t_i_m___l_l___e_c___c_c_d_m_a_r_e_q_u_e_s_t.html',1,'']]],
  ['channel_11',['CHANNEL',['../group___d_m_a___l_l___e_c___c_h_a_n_n_e_l.html',1,'']]],
  ['channel_12',['Channel',['../group___t_i_m___l_l___e_c___c_h_a_n_n_e_l.html',1,'']]],
  ['channel_20_2d_20sampling_20time_13',['Channel - Sampling time',['../group___a_d_c___l_l___e_c___c_h_a_n_n_e_l___s_a_m_p_l_i_n_g_t_i_m_e.html',1,'']]],
  ['channel_20cc_20state_14',['Channel CC State',['../group___channel___c_c___state.html',1,'']]],
  ['circularbuffer_20functions_15',['CircularBuffer functions',['../group__platform___circular_buffer.html',1,'']]],
  ['clear_20flags_20defines_16',['Clear Flags Defines',['../group___p_w_r___l_l___e_c___c_l_e_a_r___f_l_a_g.html',1,'(Global Namespace)'],['../group___r_c_c___l_l___e_c___c_l_e_a_r___f_l_a_g.html',1,'(Global Namespace)']]],
  ['clock_20division_17',['Clock Division',['../group___t_i_m___l_l___e_c___c_l_o_c_k_d_i_v_i_s_i_o_n.html',1,'']]],
  ['clock_20phase_18',['Clock Phase',['../group___s_p_i___l_l___e_c___p_h_a_s_e.html',1,'(Global Namespace)'],['../group___u_s_a_r_t___l_l___e_c___p_h_a_s_e.html',1,'(Global Namespace)']]],
  ['clock_20polarity_19',['Clock Polarity',['../group___i2_s___l_l___e_c___p_o_l_a_r_i_t_y.html',1,'(Global Namespace)'],['../group___s_p_i___l_l___e_c___p_o_l_a_r_i_t_y.html',1,'(Global Namespace)'],['../group___u_s_a_r_t___l_l___e_c___p_o_l_a_r_i_t_y.html',1,'(Global Namespace)']]],
  ['clock_20source_20',['Clock Source',['../group___t_i_m___l_l___e_c___c_l_o_c_k_s_o_u_r_c_e.html',1,'']]],
  ['cmsis_21',['CMSIS',['../group___c_m_s_i_s.html',1,'']]],
  ['cmsis_20core_20instruction_20interface_22',['CMSIS Core Instruction Interface',['../group___c_m_s_i_s___core___instruction_interface.html',1,'']]],
  ['cmsis_20core_20register_20access_20functions_23',['CMSIS Core Register Access Functions',['../group___c_m_s_i_s___core___reg_acc_functions.html',1,'']]],
  ['cmsis_20global_20defines_24',['CMSIS Global Defines',['../group___c_m_s_i_s__glob__defs.html',1,'']]],
  ['cmsis_20simd_20intrinsics_25',['CMSIS SIMD Intrinsics',['../group___c_m_s_i_s___s_i_m_d__intrinsics.html',1,'']]],
  ['cmsis_5fdevice_26',['CMSIS_Device',['../group___c_m_s_i_s___device.html',1,'']]],
  ['coarse_20digital_20calibration_20sign_27',['Coarse digital calibration sign',['../group___r_t_c___l_l___e_c___c_a_l_i_b___s_i_g_n.html',1,'']]],
  ['common_20write_20and_20read_20registers_20macros_28',['Common write and read registers Macros',['../group___a_d_c___l_l___e_m___w_r_i_t_e___r_e_a_d.html',1,'']]],
  ['common_20write_20and_20read_20registers_20macros_29',['Common Write and read registers Macros',['../group___c_r_c___l_l___e_m___w_r_i_t_e___r_e_a_d.html',1,'']]],
  ['common_20write_20and_20read_20registers_20macros_30',['Common Write and read registers macros',['../group___d_m_a___l_l___e_m___w_r_i_t_e___r_e_a_d.html',1,'']]],
  ['common_20write_20and_20read_20registers_20macros_31',['Common Write and read registers Macros',['../group___e_x_t_i___l_l___e_m___w_r_i_t_e___r_e_a_d.html',1,'(Global Namespace)'],['../group___g_p_i_o___l_l___e_m___w_r_i_t_e___r_e_a_d.html',1,'(Global Namespace)'],['../group___i2_c___l_l___e_m___w_r_i_t_e___r_e_a_d.html',1,'(Global Namespace)'],['../group___i2_s___l_l___e_m___w_r_i_t_e___r_e_a_d.html',1,'(Global Namespace)'],['../group___i_w_d_g___l_l___e_m___w_r_i_t_e___r_e_a_d.html',1,'(Global Namespace)']]],
  ['common_20write_20and_20read_20registers_20macros_32',['Common write and read registers Macros',['../group___p_w_r___l_l___e_m___w_r_i_t_e___r_e_a_d.html',1,'']]],
  ['common_20write_20and_20read_20registers_20macros_33',['Common Write and read registers Macros',['../group___r_c_c___l_l___e_m___w_r_i_t_e___r_e_a_d.html',1,'(Global Namespace)'],['../group___r_t_c___l_l___e_m___w_r_i_t_e___r_e_a_d.html',1,'(Global Namespace)'],['../group___s_p_i___l_l___e_m___w_r_i_t_e___r_e_a_d.html',1,'(Global Namespace)'],['../group___t_i_m___l_l___e_m___w_r_i_t_e___r_e_a_d.html',1,'(Global Namespace)'],['../group___u_s_a_r_t___l_l___e_m___w_r_i_t_e___r_e_a_d.html',1,'(Global Namespace)']]],
  ['common_20write_20and_20read_20registers_20macros_34',['Common Write and read registers macros',['../group___w_w_d_g___l_l___e_m___w_r_i_t_e___r_e_a_d.html',1,'']]],
  ['communication_20direction_35',['Communication Direction',['../group___u_s_a_r_t___l_l___e_c___d_i_r_e_c_t_i_o_n.html',1,'']]],
  ['complex_20conjugate_20_20_20_20_20_20_20_20_3cbr_3e_36',['Complex Conjugate        &lt;br&gt;',['../group__cmplx__conj.html',1,'']]],
  ['complex_20dot_20product_20_20_20_20_3cbr_3e_37',['Complex Dot Product    &lt;br&gt;',['../group__cmplx__dot__prod.html',1,'']]],
  ['complex_20fft_20functions_20_20_20_3cbr_3e_38',['Complex FFT Functions   &lt;br&gt;',['../group___complex_f_f_t.html',1,'']]],
  ['complex_20fft_20tables_20_20_3cbr_3e_39',['Complex FFT Tables  &lt;br&gt;',['../group___c_f_f_t___c_i_f_f_t.html',1,'']]],
  ['complex_20magnitude_20_20_20_20_3cbr_3e_40',['Complex Magnitude    &lt;br&gt;',['../group__cmplx__mag.html',1,'']]],
  ['complex_20magnitude_20squared_20_20_20_20_20_20_20_20_3cbr_3e_41',['Complex Magnitude Squared        &lt;br&gt;',['../group__cmplx__mag__squared.html',1,'']]],
  ['complex_20math_20functions_42',['Complex Math Functions',['../group__group_cmplx_math.html',1,'']]],
  ['complex_20matrix_20multiplication_20_20_20_20_20_3cbr_3e_43',['Complex Matrix Multiplication     &lt;br&gt;',['../group___cmplx_matrix_mult.html',1,'']]],
  ['complex_2dby_2dcomplex_20multiplication_20_20_20_20_20_20_20_20_3cbr_3e_44',['Complex-by-Complex Multiplication        &lt;br&gt;',['../group___cmplx_by_cmplx_mult.html',1,'']]],
  ['complex_2dby_2dreal_20multiplication_20_20_20_20_20_20_20_20_3cbr_3e_45',['Complex-by-Real Multiplication        &lt;br&gt;',['../group___cmplx_by_real_mult.html',1,'']]],
  ['configuration_46',['Configuration',['../group___d_m_a___l_l___e_f___configuration.html',1,'(Global Namespace)'],['../group___i2_c___l_l___e_f___configuration.html',1,'(Global Namespace)'],['../group___i2_s___l_l___e_f___configuration.html',1,'(Global Namespace)'],['../group___i_w_d_g___l_l___e_f___configuration.html',1,'(Global Namespace)'],['../group___p_w_r___l_l___e_f___configuration.html',1,'(Global Namespace)'],['../group___r_t_c___l_l___e_f___configuration.html',1,'(Global Namespace)'],['../group___s_p_i___l_l___e_f___configuration.html',1,'(Global Namespace)'],['../group___w_w_d_g___l_l___e_f___configuration.html',1,'(Global Namespace)']]],
  ['configuration_20functions_47',['Configuration functions',['../group___u_s_a_r_t___l_l___e_f___configuration.html',1,'']]],
  ['configuration_20functions_20related_20to_20half_20duplex_20feature_48',['Configuration functions related to Half Duplex feature',['../group___u_s_a_r_t___l_l___e_f___configuration___half_duplex.html',1,'']]],
  ['configuration_20functions_20related_20to_20irda_20feature_49',['Configuration functions related to Irda feature',['../group___u_s_a_r_t___l_l___e_f___configuration___i_r_d_a.html',1,'']]],
  ['configuration_20functions_20related_20to_20lin_20feature_50',['Configuration functions related to LIN feature',['../group___u_s_a_r_t___l_l___e_f___configuration___l_i_n.html',1,'']]],
  ['configuration_20functions_20related_20to_20smartcard_20feature_51',['Configuration functions related to Smartcard feature',['../group___u_s_a_r_t___l_l___e_f___configuration___smartcard.html',1,'']]],
  ['configuration_20of_20adc_20hierarchical_20scope_3a_20adc_20instance_52',['Configuration of ADC hierarchical scope: ADC instance',['../group___a_d_c___l_l___e_f___configuration___a_d_c___instance.html',1,'']]],
  ['configuration_20of_20adc_20hierarchical_20scope_3a_20channels_53',['Configuration of ADC hierarchical scope: channels',['../group___a_d_c___l_l___e_f___configuration___channels.html',1,'']]],
  ['configuration_20of_20adc_20hierarchical_20scope_3a_20common_20to_20several_20adc_20instances_54',['Configuration of ADC hierarchical scope: common to several ADC instances',['../group___a_d_c___l_l___e_f___configuration___a_d_c___common.html',1,'']]],
  ['configuration_20of_20adc_20hierarchical_20scope_3a_20group_20injected_55',['Configuration of ADC hierarchical scope: group injected',['../group___a_d_c___l_l___e_f___configuration___a_d_c___group___injected.html',1,'']]],
  ['configuration_20of_20adc_20hierarchical_20scope_3a_20group_20regular_56',['Configuration of ADC hierarchical scope: group regular',['../group___a_d_c___l_l___e_f___configuration___a_d_c___group___regular.html',1,'']]],
  ['configuration_20of_20adc_20hierarchical_20scope_3a_20multimode_57',['Configuration of ADC hierarchical scope: multimode',['../group___a_d_c___l_l___e_f___configuration___a_d_c___multimode.html',1,'']]],
  ['configuration_20of_20adc_20transversal_20scope_3a_20analog_20watchdog_58',['Configuration of ADC transversal scope: analog watchdog',['../group___a_d_c___l_l___e_f___configuration___a_d_c___analog_watchdog.html',1,'']]],
  ['configuration_5fsection_5ffor_5fcmsis_59',['Configuration_section_for_CMSIS',['../group___configuration__section__for___c_m_s_i_s.html',1,'']]],
  ['controller_20functions_60',['Controller Functions',['../group__group_controller.html',1,'']]],
  ['convert_2016_2dbit_20integer_20value_20_20_20_20_3cbr_3e_61',['Convert 16-bit Integer value    &lt;br&gt;',['../group__q15__to__x.html',1,'']]],
  ['convert_2032_2dbit_20floating_20point_20value_20_20_20_20_3cbr_3e_62',['Convert 32-bit floating point value    &lt;br&gt;',['../group__float__to__x.html',1,'']]],
  ['convert_2032_2dbit_20integer_20value_20_20_20_20_3cbr_3e_63',['Convert 32-bit Integer value    &lt;br&gt;',['../group__q31__to__x.html',1,'']]],
  ['convert_208_2dbit_20integer_20value_20_20_20_20_3cbr_3e_64',['Convert 8-bit Integer value    &lt;br&gt;',['../group__q7__to__x.html',1,'']]],
  ['convert_20dmaxstreamy_65',['Convert DMAxStreamy',['../group___d_m_a___l_l___e_m___c_o_n_v_e_r_t___d_m_ax_c_h_a_n_n_e_ly.html',1,'']]],
  ['convert_20helper_20macros_66',['Convert helper Macros',['../group___r_t_c___l_l___e_m___convert.html',1,'']]],
  ['convolution_20_20_20_20_3cbr_3e_67',['Convolution    &lt;br&gt;',['../group___conv.html',1,'']]],
  ['core_20debug_20registers_20_28coredebug_29_68',['Core Debug Registers (CoreDebug)',['../group___c_m_s_i_s___core_debug.html',1,'']]],
  ['core_20definitions_69',['Core Definitions',['../group___c_m_s_i_s__core__base.html',1,'']]],
  ['core_20register_20bit_20field_20macros_70',['Core register bit field macros',['../group___c_m_s_i_s__core__bitfield.html',1,'']]],
  ['correlation_20_20_20_20_3cbr_3e_71',['Correlation    &lt;br&gt;',['../group___corr.html',1,'']]],
  ['cortex_72',['CORTEX',['../group___c_o_r_t_e_x.html',1,'(Global Namespace)'],['../group___c_o_r_t_e_x___l_l.html',1,'(Global Namespace)']]],
  ['cortex_20_5fsystick_20clock_20source_73',['CORTEX _SysTick clock source',['../group___c_o_r_t_e_x___sys_tick__clock__source.html',1,'']]],
  ['cortex_20exported_20constants_74',['CORTEX Exported Constants',['../group___c_o_r_t_e_x___exported___constants.html',1,'(Global Namespace)'],['../group___c_o_r_t_e_x___l_l___exported___constants.html',1,'(Global Namespace)']]],
  ['cortex_20exported_20functions_75',['CORTEX Exported Functions',['../group___c_o_r_t_e_x___l_l___exported___functions.html',1,'']]],
  ['cortex_20exported_20types_76',['Cortex Exported Types',['../group___c_o_r_t_e_x___exported___types.html',1,'']]],
  ['cortex_20mpu_20instruction_20access_77',['CORTEX MPU Instruction Access',['../group___c_o_r_t_e_x___m_p_u___instruction___access.html',1,'']]],
  ['cortex_20mpu_20instruction_20access_20bufferable_78',['CORTEX MPU Instruction Access Bufferable',['../group___c_o_r_t_e_x___m_p_u___access___bufferable.html',1,'']]],
  ['cortex_20mpu_20instruction_20access_20cacheable_79',['CORTEX MPU Instruction Access Cacheable',['../group___c_o_r_t_e_x___m_p_u___access___cacheable.html',1,'']]],
  ['cortex_20mpu_20instruction_20access_20shareable_80',['CORTEX MPU Instruction Access Shareable',['../group___c_o_r_t_e_x___m_p_u___access___shareable.html',1,'']]],
  ['cortex_20mpu_20region_20enable_81',['CORTEX MPU Region Enable',['../group___c_o_r_t_e_x___m_p_u___region___enable.html',1,'']]],
  ['cortex_20mpu_20region_20number_82',['CORTEX MPU Region Number',['../group___c_o_r_t_e_x___m_p_u___region___number.html',1,'']]],
  ['cortex_20mpu_20region_20permission_20attributes_83',['CORTEX MPU Region Permission Attributes',['../group___c_o_r_t_e_x___m_p_u___region___permission___attributes.html',1,'']]],
  ['cortex_20mpu_20region_20size_84',['CORTEX MPU Region Size',['../group___c_o_r_t_e_x___m_p_u___region___size.html',1,'']]],
  ['cortex_20preemption_20priority_20group_85',['CORTEX Preemption Priority Group',['../group___c_o_r_t_e_x___preemption___priority___group.html',1,'']]],
  ['cortex_20private_20macros_86',['CORTEX Private Macros',['../group___c_o_r_t_e_x___private___macros.html',1,'']]],
  ['cortex_5fexported_5ffunctions_87',['CORTEX_Exported_Functions',['../group___c_o_r_t_e_x___exported___functions.html',1,'']]],
  ['cortex_5fexported_5ffunctions_5fgroup1_88',['CORTEX_Exported_Functions_Group1',['../group___c_o_r_t_e_x___exported___functions___group1.html',1,'']]],
  ['cortex_5fexported_5ffunctions_5fgroup2_89',['CORTEX_Exported_Functions_Group2',['../group___c_o_r_t_e_x___exported___functions___group2.html',1,'']]],
  ['cosine_90',['Cosine',['../group__cos.html',1,'']]],
  ['counter_20clock_20selection_91',['Counter clock selection',['../group___t_i_m___l_l___e_f___clock___selection.html',1,'']]],
  ['counter_20direction_92',['Counter Direction',['../group___t_i_m___l_l___e_c___c_o_u_n_t_e_r_d_i_r_e_c_t_i_o_n.html',1,'']]],
  ['counter_20mode_93',['Counter Mode',['../group___t_i_m___l_l___e_c___c_o_u_n_t_e_r_m_o_d_e.html',1,'']]],
  ['crc_94',['CRC',['../group___c_r_c.html',1,'(Global Namespace)'],['../group___c_r_c___l_l.html',1,'(Global Namespace)']]],
  ['crc_20configuration_20functions_95',['CRC Configuration functions',['../group___c_r_c___l_l___e_f___configuration.html',1,'']]],
  ['crc_20exported_20functions_96',['CRC Exported Functions',['../group___c_r_c___exported___functions.html',1,'(Global Namespace)'],['../group___c_r_c___l_l___exported___functions.html',1,'(Global Namespace)']]],
  ['crc_20exported_20macros_97',['CRC Exported Macros',['../group___c_r_c___exported___macros.html',1,'(Global Namespace)'],['../group___c_r_c___l_l___exported___macros.html',1,'(Global Namespace)']]],
  ['crc_20exported_20types_98',['CRC Exported Types',['../group___c_r_c___exported___types.html',1,'']]],
  ['crc_20handle_20structure_20definition_20_20_20_3cbr_3e_99',['CRC Handle Structure definition   &lt;br&gt;',['../group___c_r_c___exported___types___group2.html',1,'']]],
  ['crc_20management_100',['CRC Management',['../group___s_p_i___l_l___e_f___c_r_c___management.html',1,'']]],
  ['crc_20private_20constants_101',['CRC Private Constants',['../group___c_r_c___private___constants.html',1,'']]],
  ['crc_20private_20defines_102',['CRC Private Defines',['../group___c_r_c___private___defines.html',1,'']]],
  ['crc_20private_20functions_103',['CRC Private Functions',['../group___c_r_c___private___functions.html',1,'']]],
  ['crc_20private_20functions_20prototypes_104',['CRC Private Functions Prototypes',['../group___c_r_c___private___functions___prototypes.html',1,'']]],
  ['crc_20private_20macros_105',['CRC Private Macros',['../group___c_r_c___private___macros.html',1,'']]],
  ['crc_20private_20types_106',['CRC Private Types',['../group___c_r_c___private___types.html',1,'']]],
  ['crc_20private_20variables_107',['CRC Private Variables',['../group___c_r_c___private___variables.html',1,'']]],
  ['crc_20state_20structure_20definition_108',['CRC State Structure definition',['../group___c_r_c___exported___types___group1.html',1,'']]],
  ['critical_20section_20function_109',['critical section function',['../group__platform__critical.html',1,'']]],
  ['critical_20section_20hal_20functions_110',['Critical Section HAL functions',['../group__hal__critical.html',1,'']]],
  ['criticalsectionlock_20functions_111',['CriticalSectionLock functions',['../group__platform___critical_section_lock.html',1,'']]],
  ['cthunk_20class_112',['CThunk class',['../group__platform___c_thunk.html',1,'']]],
  ['currenttargetmem_113',['CURRENTTARGETMEM',['../group___d_m_a___l_l___e_c___c_u_r_r_e_n_t_t_a_r_g_e_t_m_e_m.html',1,'']]]
];
